"use client";

import Footer from "./components/common/Footer";
import "@/app/styles/globals.css";
import "@/app/styles/flex.css";
import "@/app/styles/global/style.css";
import "@/app/styles/global/plugins/bootstrap-grid.css";
import "@/app/styles/global/plugins/font-awesome.min.css";
import "@/app/styles/global/plugins/swiper.min.css";
import "@/app/styles/scss/style.scss";
import HeaderSwitcher from "./components/common/HeaderSwitcher";
import "react-toastify/dist/ReactToastify.css";
import { GoogleAnalytics } from '@next/third-parties/google'

const RootLayout = ({ children }) => {

  return (
    <html lang="en">
      <head>
        {/* External stylesheets and scripts */}
        <script
          async
          src="https://unpkg.com/swiper/swiper-bundle.min.js"
        ></script>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Wattle Sol</title>
        <meta name="description" content="Generated by Sarah Patris" />
      </head>
      <body>
        <GoogleAnalytics gaId="G-MNF6F37L2P" />
        <HeaderSwitcher />
        <div className="mil-wrapper">{children}</div>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
