'use client';

import Footer from './components/common/Footer';
import '@/app/styles/globals.css';
import '@/app/styles/flex.css';
import '@/app/styles/global/style.css';
import '@/app/styles/global/plugins/bootstrap-grid.css';
import '@/app/styles/global/plugins/font-awesome.min.css';
import '@/app/styles/global/plugins/swiper.min.css';
import '@/app/styles/scss/style.scss';
import HeaderSwitcher from './components/common/HeaderSwitcher';
import 'react-toastify/dist/ReactToastify.css';
import { useEffect } from 'react';

const RootLayout = ({ children }) => {
  useEffect(() => {
    // Add Dialogflow widget script dynamically
    const script = document.createElement('script');
    script.src =
      'https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/df-messenger.js';
    script.async = true;
    document.body.appendChild(script);

    script.onload = () => {
      // Ensure the script has loaded before creating the widget
      const dfMessenger = document.createElement('df-messenger');
      dfMessenger.setAttribute('project-id', 'wattle-sol-433700');
      dfMessenger.setAttribute(
        'agent-id',
        '05e3e682-fec3-4b74-ab38-315e0e0cc147'
      );
      dfMessenger.setAttribute('language-code', 'en');
      dfMessenger.setAttribute('max-query-length', '-1');

      // Apply custom styles to the chat widget
      dfMessenger.style.zIndex = '999';
      dfMessenger.style.position = 'fixed';
      dfMessenger.style.bottom = '30px';
      dfMessenger.style.right = '30px';
      dfMessenger.style.setProperty('--df-messenger-font-color', '#000');
      dfMessenger.style.setProperty(
        '--df-messenger-font-family',
        'Google Sans'
      );
      dfMessenger.style.setProperty(
        '--df-messenger-chat-background',
        '#f3f6fc'
      );
      dfMessenger.style.setProperty(
        '--df-messenger-message-user-background',
        '#d3e3fd'
      );
      dfMessenger.style.setProperty(
        '--df-messenger-message-bot-background',
        '#fff'
      );
      dfMessenger.style.setProperty('--df-messenger-min-width', '600px');
      dfMessenger.style.setProperty('--df-messenger-max-width', '600px');
      dfMessenger.style.setProperty('--df-messenger-min-height', '500px');
      dfMessenger.style.setProperty('--df-messenger-max-height', '700px');

      document.body.appendChild(dfMessenger);
    };
  }, []);

  return (
    <html lang="en">
      <head>
        {/* External stylesheets and scripts */}
        <link
          rel="stylesheet"
          href="https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/themes/df-messenger-default.css"
        />
        <script
          async
          src="https://unpkg.com/swiper/swiper-bundle.min.js"
        ></script>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Wattle Sol</title>
        <meta name="description" content="Generated by Next.js" />
      </head>
      <body>
        <HeaderSwitcher />
        <div className="mil-wrapper">{children}</div>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
