import Footer from './components/common/Footer';
import '@/app/styles/globals.css';
import '@/app/styles/flex.css';
import '@/app/styles/global/style.css';
import '@/app/styles/global/plugins/bootstrap-grid.css';
import '@/app/styles/global/plugins/font-awesome.min.css';
import '@/app/styles/global/plugins/swiper.min.css';
import '@/app/styles/scss/style.scss';
import HeaderSwitcher from './components/common/HeaderSwitcher';
import 'react-toastify/dist/ReactToastify.css';


const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Wattle Sol</title>
        <meta name="description" content="Generated by Next.js" />
      </head>
      <body>
        {/* <ToastContainer> */}
          <HeaderSwitcher />
          <div className="mil-wrapper">{children}</div>
          <Footer />
        {/* </ToastContainer> */}
      </body>
    </html>
  );
};

export default RootLayout;
